### ISSUE TITLE
Make AsyncDuneClient

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/dune-client#28]
People want async, especially in scenarios like what this package offers. This will require a bigger change and we also want to make it possible that non-async users can have their non-async version of the client. I would propose creating a whole new class `AsyncDuneClient`. Unfortunately this will results in some vaguely duplicated code, but I believe it is worth it and non-non async stuff can eventually be phased out.

**Comment by eliseygusev** [comment]
Hi! I've made a try on AsyncDuneClient (can be found here https://github.com/eliseygusev/dune-client/tree/async-client), but inbefore putting it into review, wanted to test for a bit. Unfortunately, seems like API keys are not available for everyone, do you mind helping me to test the functionality?

Alternatively, I can make a PR and we will start discussing the details there

**Comment by bh2smith** [comment]
Hey yea! I just took a look and I wold say its pretty good. Please feel free to make a PR here. It looks like your file `async_client.py` has what it needs (I haven't looked closely at the other files). Please send a PR I would be very happy to take a look!

**Comment by bh2smith** [comment]
One additional thing to keep in mind is that dune has limits of 3 parallel executions for non pro accounts and, I think, 7 for pro accounts. So we may want to account for these limitations on the client side or at least handle the errors gracefully.

**Comment by bh2smith** [comment]
I also like you addition is "session"

**Comment by eliseygusev** [comment]
made a WIP https://github.com/cowprotocol/dune-client/pull/31 PR. once we settle on all the implementation details I would elaborate/update comments.

**Comment by bh2smith** [comment]
Closed by #31
