### ISSUE TITLE
Add is_complete method to ExecutionState

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/dune-client#30]
def is_complete(self) -> bool:
        return self == ExecutionState.COMPLETED

**Comment by bhavy2202** [comment]
Please assign me

**Comment by bh2smith** [comment]
Done, Thanks in advance!

**Comment by bhavy2202** [comment]
Will this issue be hacktoberfest accepted?

**Comment by bh2smith** [comment]
I could try and add the repo to the event by tagging it.

**Comment by bh2smith** [comment]
I added the hacktoberfest topic to the project description. Should be good to go. Will confirm on my own.

**Comment by bh2smith** [comment]
Seems to have worked! Happy hacking.

**Comment by bh2smith** [comment]
I'm guess since October is over that you have decided not to do this?
